### ISSUE TITLE
Lighthouse fails to parse logs generated on Linux with DynamoRIO 7.0.0-RC1

### ISSUE THREAD

**Issue by fmagin** [gaasedelen/lighthouse#10]
A log file that is generated with DynamoRIO 7.0.0-RC1 on Linux has a different header than on Windows and Lighthouse fails to account for this.
The first lines on those log files look like this and lack some entries (probably) due to this: https://github.com/DynamoRIO/dynamorio/blob/master/ext/drcovlib/modules.c#L388

```
DRCOV VERSION: 2
DRCOV FLAVOR: drcov-64
Module Table: version 2, count 6
Columns: id, base, end, entry, path
0, 0x0000000000400000, 0x0000000000621000, 0x0000000000404030, /usr/bin/ls
```

Actual error thrown is
```
line 307, in _parse_module_v2
    self.checksum  = int(data[4], 16)
ValueError: invalid literal for int() with base 16: '/usr/bin/ls'
```

[log.zip](https://github.com/gaasedelen/lighthouse/files/1261439/log.zip)

**Comment by gaasedelen** [comment]
Fixed in cfef581, will be included in the v0.6 release.

Thanks for the report :-)
