### ISSUE TITLE
Binary Ninja plugin errors with metaclass conflict

### ISSUE THREAD

**Issue by fabianfreyer** [gaasedelen/lighthouse#100]
Log when starting:

```
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/lighthouse_plugin.py", line 1, in <module>
    from lighthouse.util.log import logging_started, start_logging
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/lighthouse/util/__init__.py", line 3, in <module>
    from .debug import *
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/lighthouse/util/debug.py", line 6, in <module>
    from .log import lmsg
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/lighthouse/util/log.py", line 6, in <module>
    from .disassembler import disassembler
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/lighthouse/util/disassembler/__init__.py", line 31, in <module>
    from .binja_api import BinjaCoreAPI, BinjaContextAPI
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/lighthouse/util/disassembler/binja_api.py", line 356, in <module>
    class DockableWidget(QtWidgets.QWidget, DockContextHandler):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Python plugin 'lighthouse_plugin' could not be loaded
```

**Comment by gaasedelen** [comment]
Can you tell me what version of python your binja install is using? I imagine this crash is the result of some sort of python incompatibility/regression on the binja side. 

In your binja console:
```
import sys
print(sys.version)
```

Fwiw, on Windows + Python 3.9.2, Lighthouse seems to be working. I know Binja broke support for Python 3.6 (at least, for Qt-based plugins) within the past 6 months. And I'm wondering if something similar happened again.

**Comment by fabianfreyer** [comment]
```
>>> import sys
... print(sys.version)
... 
3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)]
```

This is on MacOs, with Binja Version 2.3.2741-dev (2021-04-12 23:10:18)

**Comment by frederikptk** [comment]
In case you haven't solved the problem yet, I also encountered this problem and was able to solve it. I copied the "lighthouse" folder and "lighthouse_plugin.py" directly into the "plugins" folder of Binary Ninja. Starting Binary Ninja then results in the above error. The solution for me was to create a "lighthouse" folder in Binary Ninja's "plugin" folder and copy the above 2 elements into this subfolder.

**Comment by gaasedelen** [comment]
Sorry, the reason why this hasn't been 'fixed' is that I haven't actually been able to reproduce the issue. I think there might be some sort of conflict in your environment, such as a secondary version of PyQt/PySide in your python install...

Otherwise, it's possible this is occurring because some sort of plugin conflict? I am not sure...

If you're still encountering issues or figured out what the conflict was, let me know.

**Comment by mkrasnitski** [comment]
Can confirm I experience the same issue when attempting to install. I get the same backtrace as OP, on python 3.9.6 and Binja stable build 2.4.2846. I have python-pyqt5 and python-pyqt5-sip installed from the Arch repos, but not the qt4 equivalents. They were installed as dependencies for other packages though, so removing them would be inconvenient.

**Comment by gaasedelen** [comment]
Thanks! That's good info, I suspected it might be some sort of overlapping Qt install issue.

I'll see if I can reproduce it and come up with a reasonable workaround.

**Comment by gaasedelen** [comment]
This should be resolved now. 

The fix is on the develop branch, but hopefully I'll be merging develop onto master as v0.9.2 in the coming week or two.

**Comment by mkrasnitski** [comment]
Can confirm, the plugin loads fine now. Thanks!
