### ISSUE TITLE
Unknown or unsupported disassembler!

### ISSUE THREAD

**Issue by H4niz** [gaasedelen/lighthouse#107]
I met this error: `Unknown or unsupported disassembler!`, I found a issue that said I should use python 3.7.7. I did it however It's still not work!

The error:
Please check the Edit/Plugins menu for more informaton.

> C:\Users\h4niz\AppData\Roaming\Hex-Rays\IDA Pro\plugins\lighthouse_plugin.py: Unknown or unsupported disassembler!
> Traceback (most recent call last):
>   File "D:\DIRECTORY\Tools\IDAPro 7.6 SP1\IDA Pro 7.6\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
>     exec(code, g)
>   File "C:/Users/h4niz/AppData/Roaming/Hex-Rays/IDA Pro/plugins/lighthouse_plugin.py", line 1, in <module>
>     from lighthouse.util.log import logging_started, start_logging
>   File "C:/Users/h4niz/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\__init__.py", line 3, in <module>
>     from .debug import *
>   File "C:/Users/h4niz/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\debug.py", line 6, in <module>
>     from .log import lmsg
>   File "C:/Users/h4niz/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\log.py", line 6, in <module>
>     from .disassembler import disassembler
>   File "C:/Users/h4niz/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\disassembler\__init__.py", line 42, in <module>
>     raise NotImplementedError("Unknown or unsupported disassembler!")
> NotImplementedError: Unknown or unsupported disassembler!

IDA version: 7.6
Python version:

> Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] 
> IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>

**Comment by gaasedelen** [comment]
Hmm, I just downloaded IDA 7.6 SP1 to test this and was not able to reproduce the issue.

Could you try removing the 'try/except' wrapper from the code below and see what the crashing callstack is then...?

https://github.com/gaasedelen/lighthouse/blob/7245a2d2c4e84351cd259ed81dafa4263167909a/plugins/lighthouse/util/disassembler/__init__.py#L13-L24

**Comment by H4niz** [comment]
Hi @gaasedelen, I removed the `try/except` statement and `lighthouse` was imported successfully!
Thanks!
