### ISSUE TITLE
"drcov version: 3" is unsupported

### ISSUE THREAD

**Issue by BlueAmulet** [gaasedelen/lighthouse#112]
"Version 3 changes module offsets to be offsets from the module segment, rather than the whole module base as in version 2."

https://github.com/DynamoRIO/dynamorio/pull/5094
https://github.com/DynamoRIO/dynamorio/pull/5136

**Comment by luoyanghero** [comment]
Lighthouse cannot support drcov-version-3.
I tried lighthouse `lighthouse-0.9.2`, dynamorio `DynamoRIO-Windows-9.0.1`, not ok.
I tried lighthouse `lighthouse-0.9.2`, dynamorio `DynamoRIO-Windows-8.0.18873`, ok.

**Comment by adrian-rt** [comment]
I got the same issue

**Comment by wumb0** [comment]
I am currently too lazy to write a parser for Lighthouse to handle drcov v3 but here is a dumb python script that converts drcov 3 to drcov 2. I wrote it to help me and maybe it can help you, while this issue remains open :)

[https](https://gist.github.com/wumb0/de671cc5051353fd32af4aecc811a282)[://gist.github.com/wumb0/de671cc5051353fd32af4aecc811a282](https://gist.github.com/wumb0/de671cc5051353fd32af4aecc811a282)

**Comment by zeltrax00** [comment]
I comment the line `assert self.version == 2, "Only drcov version 2 log files supported"` in `drcov.py` then it is able to load new drcov log version. Is there any potential problem ?

**Comment by mounirthabet** [comment]
hello sir the convert script not working anymore for the last version DynamoRIO-9.93.19510 I got Wrong version or bad format error once i use it

**Comment by PavelBlinnikov** [comment]
PR #137 solves this

**Comment by gaasedelen** [comment]
#137 has been merged into the develop branch, fixing this issue.
