### ISSUE TITLE
LIght house is not able to parse the file generated by drcov

### ISSUE THREAD

**Issue by bikashdash** [gaasedelen/lighthouse#117]
i already filled one issue in dynamorio regarding same. thoght to share here
 every time i generate the log file from drrun drcov tool, when i opened the log file in ida with lighthouse, it says corrupted and not able to parse it. please have a look into it.
![Malware_Research-2022-01-25-00-45-44](https://user-images.githubusercontent.com/4816640/150848844-3c91b692-0052-4c27-a251-312da7542332.png)

issue listed in dynamorio
https://github.com/DynamoRIO/dynamorio/issues/5288

coverage file

![Malware_Research-2022-01-25-00-47-34](https://user-images.githubusercontent.com/4816640/150848986-80eccddd-ae63-482d-baf5-6626494d9f59.png)

please help me on this.

**Comment by zhaopengoog** [comment]
this is a dup for [issue 112](https://github.com/gaasedelen/lighthouse/issues/112)

**Comment by sgzeng** [comment]
It works on drcov version 2 available from dynamorio 7.x 3 years ago.

**Comment by gaasedelen** [comment]
#137 has been merged into the develop branch, fixing this issue.
