### ISSUE TITLE
lighthouse creates logs, even when not used

### ISSUE THREAD

**Issue by yrp604** [gaasedelen/lighthouse#12]
I installed lighthouse, but have yet to use it for anything. However, despite not using it:

```
$ ls ~/.idapro/lighthouse_logs/ |wc -l
       5
```

Example log:
```
$ cat ~/.idapro/lighthouse_logs/lighthouse.38900.log
09-28-2017 00:26:14 |           Lighthouse |   DEBUG: Cleaning logs directory
09-28-2017 00:26:37 |            pip.utils |   DEBUG: lzma module is not available
09-28-2017 00:26:37 |              pip.vcs |   DEBUG: Registered VCS backend: git
09-28-2017 00:26:37 |              pip.vcs |   DEBUG: Registered VCS backend: hg
09-28-2017 00:26:37 |              pip.vcs |   DEBUG: Registered VCS backend: svn
09-28-2017 00:26:37 |              pip.vcs |   DEBUG: Registered VCS backend: bzr
09-28-2017 00:26:37 |    Lighthouse.STDOUT |    INFO: [+] Using already installed pip (version 9.0.1)
```

This is based off of 0.6, a1497699350c57363df13ca10ab731c0b655a106

Is this the intended behavior?

**Comment by gaasedelen** [comment]
This is technically intended behavior - logging starts when the plugin gets imported by IDA (eg, when an IDB is opened) and also proxies the IDA console output. The logs are local to your machine. The lighthouse logging mechanism should also limit the logs in the folder to ~5. 

I simply use the logging functionality when developing and debugging. I'll consider disabling logging in future releases.

Thanks for the heads up.
