### ISSUE TITLE
Usability Enhancement: Show Demangled C++ Function Names in Coverage Overview

### ISSUE THREAD

**Issue by fmagin** [gaasedelen/lighthouse#13]
Would make readability easier and makes things a bit less confusing if the function names in the Coverage Overview are the same as in the Function Window

**Comment by gaasedelen** [comment]
This has been merged into develop via pull request #15 and will be included with the v0.7 release of Lighthouse. 

I'll double check (or add) compatibility before it goes out and will close this issue once I have a chance to do so :-)

**Comment by gaasedelen** [comment]
get_short_name() should do the appropriate demangling when pulling the name from the database. It also exists from 6.8 through 7.0, so it helps simplify things.

Testing shows this to work the same, but let me know if this breaks anything on your side.
