### ISSUE TITLE
Minor bug fix regarding modules coverage.

### ISSUE THREAD

**Issue by symeonp** [gaasedelen/lighthouse#2]
Hi!

Quick issue regarding coverage, I added some extra debug info when a coverage file
matches given a module:

> -- snip --
> filename: RPCRT4.dll
> module name: gdi32.dll
> filename: LPK.dll
> module name: gdi32.dll
> filename: GDI32.dll
> -- snip --

As you can see, even though GDI32 coverage was there, it would yield "Failed to find module GDI32.dll in coverage data" . The following patch, fixes that for me:

```
diff --git a/plugin/lighthouse/parsers/drcov.py b/plugin/lighthouse/parsers/drcov.py
index 0cff331..457af96 100644
--- a/plugin/lighthouse/parsers/drcov.py
+++ b/plugin/lighthouse/parsers/drcov.py
@@ -44,7 +44,7 @@ class DrcovData(object):
 
         # locate the coverage that matches the given module_name
         for module in self.modules:
-            if module.filename == module_name:
+            if module.filename == module_name or module.filename.lower() == module_name:
                 mod_id = module.id
                 break
```

Cheers!

**Comment by symeonp** [comment]
Also, it took my ages to debug it, I literally had to exit IDA and load it again every single time bacause idaapi.require('Lighthouse') was failing. What am I missing here? Thanks :o)

**Comment by gaasedelen** [comment]
Now imagine what it's like developing plugins :-)

Thanks for the issue, this is resolved in commit 3efeca1d89ff03c7da39a548040bd917227d2d12 on develop and will be included in the next release.

**Comment by symeonp** [comment]
Fantastic, thanks so much! Excellent plugin with very clean and neat code.
Might contribute for the Intel coverage, however I really do like DynamoRIO!
Cheers

**Comment by gaasedelen** [comment]
I just noticed you had another question W.R.T ```idaapi.require(...)```. 

I've never personally used that API, but I believe you're need to query it with the name of the actual python module, eg: ```idaapi.require('lighthouse_plugin')```.

If you have any other questions, feedback, or requests, feel free to open additional issues.
