### ISSUE TITLE
LoadLibrary "CodeCoverage.dll is not a valid Win32 Application"

### ISSUE THREAD

**Issue by joswr1ght** [gaasedelen/lighthouse#20]
I'm experimenting with Lighthouse and IDA 7, but I get the following error in the console at startup:

```
LoadLibrary(C:\Program Files\IDA Demo 7.0\plugins\CodeCoverage.dll) error: %1 is not a valid Win32 application.
C:\Program Files\IDA Demo 7.0\plugins\CodeCoverage.dll: can't load file
```

I'm using Lighthouse 0.6.0. Can you make Lighthouse 0.6.1 Windows binaries available? Thanks!

**Comment by gaasedelen** [comment]
Lighthouse is an IDAPython plugin. There is nothing compiled that should be placed in your IDA directory. Please refer to the [Installation instructions](https://github.com/gaasedelen/lighthouse#installation) if you are confused about how to install Lighthouse.

`CodeCoverage.dll` is a compiled pintool meant to be used with Intel Pin. There is no difference to the Pin Tool between the v0.6 and v0.6.1 releases.

Please refer to the README regarding its usage:

https://github.com/gaasedelen/lighthouse#intel-pin-experimental
https://github.com/gaasedelen/lighthouse/tree/master/coverage/pin

Related:
https://github.com/gaasedelen/lighthouse/issues/18
