### ISSUE TITLE
Pseudocode view paint doesn't work

### ISSUE THREAD

**Issue by MJavad** [gaasedelen/lighthouse#21]
I'm on IDA 6.8 and Pseudocode view doesn't show any highlights.
What could go wrong?

**Comment by gaasedelen** [comment]
Try the [dev](https://github.com/gaasedelen/lighthouse/tree/develop) branch, I believe it should fix your issue. These changes are not yet in master.

I fixed this in commit c233f3a606a1b9adc0f5aa8a18c1f9b486a41c7f as it was reported that some builds of IDA 6.8 were behaving differently.

**Comment by MJavad** [comment]
Thanks, it worked.
There's a little inaccuracy but it's good 👍
