### ISSUE TITLE
Function name doesn't update

### ISSUE THREAD

**Issue by MJavad** [gaasedelen/lighthouse#23]
Function names doesn't update in Coverage Overview.
Also it would be nice to use your other plugin, Prefix, in Overview.

**Comment by gaasedelen** [comment]
This is technically a known issue. It's an [artifact](https://github.com/gaasedelen/lighthouse/blob/a6eac8aa8317a763427b1f2f01bbf49c24c53e1a/plugin/lighthouse/metadata.py#L33) of the metadata caching that Lighthouse does. 

I have kind of been putting off a fix for it until someone complained, but I am surprised it took this long ;P. I will be sure to fix this in v0.7

**Comment by gaasedelen** [comment]
In theory, you should be able to flush/refresh the cached metadata by loading (or reloadng) a coverage file from disk. I get that it's not great, but it's at least a temporary workaround until I put in a comprehensive fix.
