### ISSUE TITLE
Coverage Pin Tool Gives Incorrect Output For 32-bit Traces

### ISSUE THREAD

**Issue by bulaza** [gaasedelen/lighthouse#25]
The coverage Pin tool outputs address incorrectly for 32 bit traces. 

I think this can be fixed by explicitly casting ADDRINTs image.low_ and image.high_ at https://github.com/gaasedelen/lighthouse/blob/master/coverage/pin/CodeCoverage.cpp#L208 to to uint64_t, as the format string calls for that, and if we're on a 32 bit trace, the format string will pull too much off the stack - and will also break outputting the module name. Doing so appeared to fix the issue on my system, but I haven't tested enough to issue a PR knowing it won't break anything...

**Comment by gaasedelen** [comment]
cc: @agustingianni

**Comment by agustingianni** [comment]
Interesting, thanks for the report @bulaza I will try to fix this.

**Comment by bulaza** [comment]
Also note that the OnImageLoad callback printing out address works fine, as it uses the "lx" format specifier, but the one during output uses "llx"

**Comment by gaasedelen** [comment]
This should now be fixed. I cleaned up a few other types that the compiler was throwing warnings for.

I'll build new binaries for the v0.7 release.
