### ISSUE TITLE
Feature request: a button / option to clear all paint from the database

### ISSUE THREAD

**Issue by 0xcpu** [gaasedelen/lighthouse#26]
Hi,

I consider that it will be useful to have a feature to disable painting in the disassembly.

P.S. Thank you for this great tool :+1:

**Comment by gaasedelen** [comment]
Thanks for the feedback :-)

Can you pick the scenario below that best describes your situation? I would like to better understand your use case before I go ahead and implement anything.

Scenario 1:
* You want to disable the painting capabilities altogether. You are only interested in the information the Coverage Table has to offer.

Scenario 2:
* You are looking for a way to simply *clear* the paint from your database after you are done using Lighthouse. 

Scenario 3:
* You would like to disable painting in *only* the disassembly, while keeping it active in the 'pseudocode' (or graph) view.

If none of these match what you're talking about, feel free to elaborate on how or why you would like to use this feature.

**Comment by ner0x652** [comment]
Scenario 2 is what I was thinking of. Thank you that you asked, haven't thought about other scenarios. :)

**Comment by gaasedelen** [comment]
Cool, sounds good. I'll tag this for v0.8.

**Comment by ner0x652** [comment]
Thank you very much! :+1:

**Comment by gaasedelen** [comment]
This is now available in 6a08093d2f19021542eb3e4bacad80d1872e3792 on the dev branch.
