### ISSUE TITLE
Feature request: Show decompliation status

### ISSUE THREAD

**Issue by paulsapps** [gaasedelen/lighthouse#27]
In Hex-rays decompiler you can right click and "mark as decompiled". 

In the code coverage results I'd like to see a column that shows this status or some way to filter out items that have been marked as decompiled.

**Comment by paulsapps** [comment]
I gave it a go here: https://github.com/paulsapps/lighthouse/commit/efc645e197a95f90b4c54f4432e84cceee76ea68

But I have no idea how to read the "mark as decompiled" status of a function :(

**Comment by gaasedelen** [comment]
Sorry, but I am going to veto this feature request. 

The primary reason (among others) would be that I don't think it's appropriate for me to track that in the coverage table. I don't want it to become too bloated with general purpose information.

**Comment by gaasedelen** [comment]
As for checking for the "mark as decompiled" status, underneath the hood the decompiler simply sets the function's background color to a magic (hardcoded) value. 

You could check if a function is 'decompiled' by simply checking for this value.

```
def is_decompiled(function_address):
    function = idaapi.get_func(function_address)
    if not function:
        return False
    return function.color == 0xEEFFF0
```

Alternatively, you could 'mark as decompiled' with something like the following.

```
def mark_as_decompiled(function_address):
    function = idaapi.get_func(function_address)
    if not function:
        return False
    function.color = 0xEEFFF0
    return True
```

Or by manually setting the function color via the `Edit function` dialog.

**Comment by paulsapps** [comment]
Thanks - at least I could implement this in my private version then :)
