### ISSUE TITLE
error: %1 can't load file

### ISSUE THREAD

**Issue by blue-devil** [gaasedelen/lighthouse#29]
Hello i can't make the plugin load on IDA Pro 7
I am using Windows 10 x64
It gives error like this:
LoadLibrary(C:\Program Files\IDA 7.0\plugins\CodeCoverage.dll) error: %1 not a valid Win32 application.
C:\Program Files\IDA 7.0\plugins\CodeCoverage.dll: can't load file

**Comment by gaasedelen** [comment]
Please read the instructions.

#20 https://github.com/gaasedelen/lighthouse/issues/20#issuecomment-343771189
