### ISSUE TITLE
parser  DynamoRIO-Windows-6.1.1-3 generate log file error

### ISSUE THREAD

**Issue by fr0zenrain** [gaasedelen/lighthouse#3]
DynamoRIO-Windows-6.1.1-3   x86 , the log file version mismatch?

  File "D:/IDA 6.8/plugins\lighthouse\parsers\drcov.py", line 123, in _parse_module_table_header
    version_data, count_data = field_data.split(", ")
ValueError: need more than 1 value to unpack

**Comment by gaasedelen** [comment]
Three separate individuals have reported this to, so it seems like a relatively common annoyance. 

This is now fixed by commit 952f063 on the development branch and will be included in the next major release.
