### ISSUE TITLE
No Paint in Coverage Overview Pintool OS X ia32

### ISSUE THREAD

**Issue by nsknyc** [gaasedelen/lighthouse#30]
Compiled the Codecoverage Pintool with TARGET:=ia32
for 32 bit dylib. And the Overview doesn't have the color heat map.
IDA view, does show traced instructions though.

**Comment by gaasedelen** [comment]
Sorry, I am having a hard time understanding the issue.

> And the Overview doesn't have the color heat map.

To clarify, do you mean there's no color/data in the Coverage Overview table? (the box in red below)

![Coverage Overview](https://user-images.githubusercontent.com/9522648/34446200-0cf7e5d4-eca7-11e7-86ac-cdae8235d59b.png)

> ... IDA view, does show traced instructions though.

But you do see the instructions/nodes/pseudocode getting painted?

![Painting](https://github.com/gaasedelen/lighthouse/raw/master/screenshots/painting.png)

If so, that would be very strange. I have not heard of that issue yet.

* Do you see any 'Failed to load coverage file ...' in the output text window?
* Can you provide the problematic IDB and .log coverage file? 
* What version of IDA are you using?

**Comment by nsknyc** [comment]
Using IDA 7.0 mac osx, its a 32bit binary that I disassembled. I'm thinking the issue is coming from the 32 bit version of the Codecoverage pin tool. It may not be producing proper trace.log data. The coverage overview HAS data, it is just not painted. Nodes instructions and pseudocode are painted. The 64bit does produce proper data and lighthouse produces the great results, such as your examples. There is no 'Failed to load coverage file...' in the output text window as well. I'll post up pics asap so you can see. I can provide the .log files, but the not sure if I can share the idb.

**Comment by nsknyc** [comment]
I compiled the 32 bit version of the code coverage pin tool by adding "TARGET := ia32" in the pin/source/tools/Config/makefile.config. Perhaps this is the issue?

**Comment by gaasedelen** [comment]
> The coverage overview HAS data, it is just not painted.

Thanks for the pictures! That is what I thought you were saying, but it was so unexpected/weird that I thought I wasn't understanding you correctly. There are only two points where this could be failing.

1. The code that does the color lookup for the background is somehow not working correctly which seems unlikely considering all the other table data populates fine.

https://github.com/gaasedelen/lighthouse/blob/dc7ef504dbbc8adbde94dc1de4bece7462054e74/plugin/lighthouse/ui/coverage_overview.py#L720-L729

2. The code that computes the color for the 'FunctionCoverage' objects is failing.

https://github.com/gaasedelen/lighthouse/blob/dc7ef504dbbc8adbde94dc1de4bece7462054e74/plugin/lighthouse/coverage.py#L655-L662

Either of these failing is mind boggling to me.

---

It's hard for me to diagnose without being able to reproduce the issue.

Could you try putting some print statements in the first code block I highlighted? Something like the following:

```
        # cell background color request
        elif role == QtCore.Qt.BackgroundRole:
            function_address  = self.row2func[index.row()]
            function_coverage = self._director.coverage.functions.get(
                function_address,
                self._blank_coverage
            )

            print "-"*60
            print "Function Address: 0x%X" % function_address
            print "Function Coverage Address: 0x%X" % function_coverage.address
            print "Functiton Coverage Percent:", function_coverage.instruction_percent
            print "Function Color:", function_coverage.coverage_color.getRgb()

            return function_coverage.coverage_color
```
Open the coverage file that's acting weird and copy paste some of the prints that spew to your output window (some with and without a non-zero coverage percent if possible).

Hopefully that will give me a better idea of where the failure could be happening.

**Comment by gaasedelen** [comment]
> I compiled the 32 bit version of the code coverage pin tool by adding "TARGET := ia32" in the pin/source/tools/Config/makefile.config. Perhaps this is the issue?

No, that should be correct. I am not convinced that the 32bit pintool log file is actually the issue here since the Coverage Overview is actually showing data from the log.

**Comment by nsknyc** [comment]
Yes, that's what I thought as well. I compared it with a 64bit app's log file, (at a glance) and everything seemed well. I also decompiled the 32bit app in ida64 to see if the same happens in lighthouse. And again no paint. I'll put the print functions now and see what's up.

**Comment by nsknyc** [comment]
Ok, so the print info seems ok. It matches the percentage data and the color info reflecting it.
<img width="1440" alt="screen shot 2017-12-29 at 4 26 16 pm" src="https://user-images.githubusercontent.com/19629541/34448669-3213e7d8-ecb5-11e7-9cb4-df121ef5d791.png">

**Comment by nsknyc** [comment]
I screenshot an example where you can see the comparison of data v print. I could copy and paste the whole print if you wish

**Comment by nsknyc** [comment]
Hmm, one second. I just checked another IDB in ida64, and lighthouse is no longer paining there as well. I'm going to reset all configs, fonts colors and remove idaskin. I think there's an issue.

**Comment by gaasedelen** [comment]
Thanks, yeah okay this is really weird.

Based on your print log, the coverage colors are getting computed correctly (scenario 2) and delivered to the table correctly (scenario 1) ... but for some reason, the colors are getting swallowed by Qt 😕?!? 

This is probably a bug/behavior clash stemming from the themeing plugin(s) you are using. Lighthouse is pretty tolerant custom themes (I use them myself), but maybe something is getting overridden.

Could you provide details on what custom theme plugins/configs you are using? Perhaps this is something I'll be able to reproduce on Windows. 

Zyantific's [IDA Skins](https://github.com/zyantific/IDASkins) is the post popular one, but I stumbled across another one just the other day ...

**Comment by nsknyc** [comment]
Please close this. There's no official release of ida skins for OS X. I to modify to compile on osx. Its a conflict between both. Unfortunately, I do have another issue with lighthouse. I'll open up another ticket.
