### ISSUE TITLE
IDA and IDA64 refuses to fully close after loading a coverage log.

### ISSUE THREAD

**Issue by nsknyc** [gaasedelen/lighthouse#31]
This problem I noticed before since I first started using lighthouse. All the painting is perfect the data is perfect, but when I'm done working and decide to close IDA(or IDA64) it won't finish shutting down. It leaves me with the output windows, which i can close but cannot quit IDA. I'd have to force quit. I removed ida skins and other plugins.
Fortunately IDA does finish packing the database, so nothing is left undone.
To me it seems as if there's some loops still in process which doesn't let IDA shut down, but that is purely speculation.
version 7.0, os x 10.12.6

**Comment by nsknyc** [comment]
I'm left with this window at the end.
<img width="806" alt="screen shot 2017-12-29 at 4 58 30 pm" src="https://user-images.githubusercontent.com/19629541/34449173-326395d4-ecbb-11e7-8030-b9acb416a147.png">
 Quitting doesn't do anything. I can close the window but Ida still remains open. As I mentioned before, I'd have to force quit.

**Comment by gaasedelen** [comment]
Yep, hanging on exit is usually an indication of a thread still spinning in the background. In this case, it's most likely the painting thread not getting the termination signal, or somehow deadlocking 🤔 

It's a bit surprising that this is still an issue because I thought I [eliminated](https://github.com/gaasedelen/lighthouse/commit/177f462e8251d0fdd8001468ed66cd104b39f2e8) it awhile back. It at least isn't an issue on Windows or Linux anymore.

Thanks for the report, I'll investigate.

**Comment by nsknyc** [comment]
If there's anything I can do to help, please share. I'm not too familiar with ida's api, is there a way to see  threads still running under ida?

**Comment by gaasedelen** [comment]
@agustingianni confirmed for me that he was also experiencing the hang on MacOS (thanks!) so I was able to take a quick look at it tonight.

This issue appears to have been introduced by the v0.7 release. I am not sure why the hang doesn't occur on Windows, but it should hopefully be fixed now. I pushed the hotfix directly to master as Lighthouse v0.7.1, please download and try that.

This is probably a good time to mention that Lighthouse is best supported on Windows as that's where I develop and test it. MacOS and Linux might be a little quirky :-)

**Comment by nsknyc** [comment]
Thanks for the quick response. I'm already testing it out.

**Comment by gaasedelen** [comment]
Great, thanks for the following up.
