### ISSUE TITLE
Cannot parse logs from DRCOV in the last build of dynamorio

### ISSUE THREAD

**Issue by caballomaldito** [gaasedelen/lighthouse#36]
Tested on: IDA Pro Version 7.0.170914 Windows x64

To reproduce:

1. Download the last cronbuild for Windows

https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-7.0.17640/DynamoRIO-Windows-7.0.17640-0.zip

2. invoke drcov to generate a .log file to later insert into lighthouse ida PRO 

\dynamo\bin32\drrun.exe -t drcov -- "C:\myfile.exe"

3. Lighthouse fails to open the log file

[Lighthouse] Failed to load coverage C:/drcov.myfile.exe.07872.0000.proc.log

**Comment by gaasedelen** [comment]
Oh that's obnoxious. Thanks for the heads up, I'll push a hotfix shortly.

**Comment by gaasedelen** [comment]
This is now fixed in master.
