### ISSUE TITLE
Distribution of Compiled Pin Binaries

### ISSUE THREAD

**Issue by PeterG75** [gaasedelen/lighthouse#43]
Hi,
Thanks for the great tool but not sure if you are aware that distribution of compiled Pin binaries is not allowed as per the End User Agreement. We are only allowed to distribute the Pin Tools in a source code form.

I did not know of any other way to contact you. That is why I though I should inform you here. Thanks

**Comment by gaasedelen** [comment]
Thanks for bringing this to my attention!
