### ISSUE TITLE
Bug in loading drcov v4 trace

### ISSUE THREAD

**Issue by toshipiazza** [gaasedelen/lighthouse#45]
It seems there's a bug in loading any drcov v4 trace:

https://github.com/gaasedelen/lighthouse/blob/8e09989a671b595139b345992d8ecc6fb50e7ff7/plugin/lighthouse/parsers/drcov.py#L427-L429

The length of data ought to be 9 (I think?) on Windows:

https://github.com/DynamoRIO/dynamorio/blob/ef20472cf4c1b9fd8a62e714e42b6e22b2450077/ext/drcovlib/drcovlib.h#L209-L256

**Comment by gaasedelen** [comment]
Hilarious, not sure how you found this. Lighthouse doesn't actually ever use of that information, parsed or not.

Nonetheless, I'll fix it. Thanks for the report!
