### ISSUE TITLE
Suggestion to add into Readme correct version of Pin to download

### ISSUE THREAD

**Issue by peta909** [gaasedelen/lighthouse#46]
Hi,

Thank you for this excellent tool.
Can I suggest that you add a comment to download pin version "pin-3.4-97438" (gf90d1f746) as that is the only version that will work with your compiled CodeCoverage dlls ?

**Comment by gaasedelen** [comment]
Hmm, have you checked the [releases](https://github.com/gaasedelen/lighthouse/releases) page for this repo? It has downloads to versions built for the past few major Pin releases. This includes every release *since* Pin 3.4.

[v0.7 Release](https://github.com/gaasedelen/lighthouse/releases/tag/v0.7.0) -- Pin 3.4, 3.5
[v0.8 Release](https://github.com/gaasedelen/lighthouse/releases/tag/v0.8.0) -- Pin 3.6, 3.7

Thanks for the issue. I can improve the language/links in the README's to further clarify this in the next update or hotfix.

**Comment by computereasy** [comment]
Hi, @gaasedelen , I tried a number of Pin implementations, and only the pin-3.0 works...

All the other versions (3.4, 3.6., 3.7) throws the following issue:

    ➜  CodeCoverage ../../../pin -t obj-intel64/CodeCoverage.so -- ~/work/code/tools/codeCoverage/qs
    E: Unable to load /home/wangshua/work/code/pin-3.4-97438-gf90d1f746-gcc-linux/source/tools/CodeCoverage/obj-intel64/CodeCoverage.so: dlopen failed: cannot locate symbol
"_ZnwmSt11align_val_t" referenced by "/home/wangshua/work/code/pin-3.4-97438-gf90d1f746-gcc-linux/source/tools/CodeCoverage/obj-intel64/CodeCoverage.so"...

Any idea on that?

**Comment by computereasy** [comment]
Thanks for your prompt feedback. I am using Ubuntu 18.04 with gcc 7.3.0. I am trying to instrument 64-bit binaries.

**Comment by computereasy** [comment]
So actually the plugin works on another machine of mine, a Ubuntu 14.04 machine with `pin 3.0`, and gcc 6.4.0

**Comment by gaasedelen** [comment]
Interesting, thanks for the info. I will get a 18.04 VM setup in the next couple of days and test on that. It's possible our makefile is missing a necessary toggle for newer versions of GCC, not sure.

**Comment by computereasy** [comment]
No problem, I will setup a Ubuntu 16.04 machine and hope it would go smoothly.

**Comment by gaasedelen** [comment]
So ignoring GCC's advice to add `-faligned-new` (which yields the symbol error you pasted) to the Makefile, I used `-Wno-aligned-new` to silence the error. 

This seems to work, producing a valid Pin 3.7 pintool on Ubuntu 18.04.

**Comment by anishrajghimire** [comment]
Hello @computereasy,

I am also getting the same error.
Did you solve this error?
/sniper-7.2/sift/recorder/obj-intel64/sift_recorder: dlopen failed: cannot locate symbol "_ZnwmSt11align_val_t"

**Comment by YLSnowy** [comment]
> Hello @computereasy,
> 
> I am also getting the same error. Did you solve this error? /sniper-7.2/sift/recorder/obj-intel64/sift_recorder: dlopen failed: cannot locate symbol "_ZnwmSt11align_val_t"

hello, i am also get the same error
Did you solve this error?
Thank you all the same!

**Comment by YLSnowy** [comment]
Hi,

Thank you for this excellent tool.
But I am gettiing some peoblem.
dlopen failed: cannot locate symbol "_ZnwmSt11align_val_t"
Do you know how to solve it?

**Comment by xzx0805** [comment]
Hi,

Thank you for this excellent tool.
But I am gettiing some peoblem.
dlopen failed: cannot locate symbol "_ZnwmSt11align_val_t"
Do you know how to solve it?

> Hi,
> 
> Thank you for this excellent tool. But I am gettiing some peoblem. dlopen failed: cannot locate symbol "_ZnwmSt11align_val_t" Do you know how to solve it?

**Comment by xzx0805** [comment]
@YLSnowy @anishrajghimire @gaasedelen @computereasy @peta909 
hello, i am also get the same error
Did you solve this error?
Thank you all the same!
