### ISSUE TITLE
assertion failed: 0 != ((1 << f) & cmask)

### ISSUE THREAD

**Issue by areuu** [gaasedelen/lighthouse#52]
Hi, I found nothing in trace.log
I'm using Windows 10 x64
it gives errors like this
` A: build\Source\pin\internal-include-windows-ia32\context_windows.H: LEVEL_VM::WINDOWS_PCTXT::BaseAddrOf: 325: assertion failed: 0 != ((1 << f) & cmask)`

**Comment by gaasedelen** [comment]
This is almost certainly a bug in the PIN runtime itself - not Lighthouse.

I would try reporting the issue to the pinheads group and hope that intel fixes it in a future release.

https://software.intel.com/en-us/articles/pin-a-binary-instrumentation-tool-faq
https://groups.yahoo.com/neo/groups/pinheads/info

Alternatively, you can try DynamoRIO/Drcov!
