### ISSUE TITLE
drcov parser amd64 support

### ISSUE THREAD

**Issue by Trolldemorted** [gaasedelen/lighthouse#54]
If I understand your source code correctly this won't work for 64bit:

```python
class DrcovBasicBlock(Structure):
    """
    Parser & wrapper for basic block details as found in a drcov coverage log.

    NOTE:

      Based off the C structure as used by drcov -

        /* Data structure for the coverage info itself */
        typedef struct _bb_entry_t {
            uint   start;      /* offset of bb start from the image base */
            ushort size;
            ushort mod_id;
        } bb_entry_t;

    """
    _pack_   = 1
    _fields_ = [
        ('start',  c_uint32),
        ('size',   c_uint16),
        ('mod_id', c_uint16)
    ]
```

and the block starts are indeed incorrect when you load a drcov file with 64bit addresses.
cc @domenukk @RobertBuhren

**Comment by gaasedelen** [comment]
Sorry, I am not sure I understand the issue.

- Can you provide an elf+log testcase for me to reproduce your issue?
- What tool or script are you using to generate your coverage log?
- What OS are you running the coverage tool on? Windows/Linux/macOS?

Historically, DynamoRIO/drcov will output the *offset* of a basic block from the imagebase. Almost universally, this shouldn't be an issue for 32 or 64 bit applications... unless your application has a code segment that gets loaded > 4gb away from the imagebase??

**Comment by Trolldemorted** [comment]
I am manually producing coverage data (from a running linux kernel) and dumping it to a file, so yeah it might be a bit unusual. My testfile definitely had huge segments since I created them manually and I assumed it wouldn't matter if they are too big.

**Comment by gaasedelen** [comment]
Are you outputting the *offset* of the basic block from the loaded kernel's imagebase? Your coverage logger should not be emitting full 64bit addresses. If this does not fix your issue, then I don't really have a good answer for you at this time. 

Practically speaking, there's no way I am going to be changing the code you outlined above (sorry!). That's simply the format defined by DynamoRIO, and I am parsing it. You're welcome to try changing it in your local branch, but it will likely require a number of other changes to Lighthouse.
