### ISSUE TITLE
Is there any limitation for large number of log data?

### ISSUE THREAD

**Issue by phd18** [gaasedelen/lighthouse#57]
Hi;

Thank you for your great plugin. I want to show 1500 drcov log files; but I can't see more than 28(A-Z) coverage files in combo box. Is there any limitation to show more coverage files?

Best Regards

**Comment by gaasedelen** [comment]
Thanks for the kind words.

Looking back, I think that this is a fair suggestion and I would be open to *at least* allowing the combobox to display all loaded coverage sets. I am little hesitant to expand the shorthand range (eg, AA, AB, AC) though.

It was originally designed with this limitation as a concious decision for usability reasons. There are some comments in the director discussing the 'shorthand symbols', here is one referencing this issue:

https://github.com/gaasedelen/lighthouse/blob/675cc8738d47eb569aba7f15653f640510371dc4/plugin/lighthouse/director.py#L134-L143

Practically speaking, I wanted to deter users from loading a large number (dozens, hundreds, thousands) of coverage files individually. Scrolling through a combobox of 1500 to switch between sets does not sound fun.

The seperate batch loading is supposed to help with these cases,
