### ISSUE TITLE
How to get the Coverage Painting function

### ISSUE THREAD

**Issue by carterMgj** [gaasedelen/lighthouse#7]
Hello，my IDA is IDA_Pro 6.8 , How can I get the effect like the "Coverage Painting" show?
In my IDA disassembly,graph and Pseudocode views, there aren't code painted blue.....

Thx~

**Comment by gaasedelen** [comment]
Can you provide a sample testcase? (executable, and the collected coverage file)

**Comment by carterMgj** [comment]
Tks . The executable file and coverage file are saved in https://github.com/carterMgj/script/blob/master/tt.zip
     I want to know about how you create the coverage file, I guess the key point of my problem is here.
     I used DynamoRIO to get the coverage file , I did it follow this url : http://www.netfairy.net/?post=292

**Comment by gaasedelen** [comment]
I tried the zip you provided in IDA 6.8 and it appears to be working for me:

![zip](http://i.imgur.com/1DJ01vz.png)

Are you using the latest version of Lighthouse?

**Comment by carterMgj** [comment]
ok, I download the lighthouse again, and it can draw in assembly code view, but can't draw in disassembly code view, like below's image show:

![1](https://user-images.githubusercontent.com/18275695/28554104-1ff49860-712a-11e7-8792-c14b3ac06a08.png)

I use IDA_Pro 6.8, but it can work normally in IDA 6.9.......

**Comment by gaasedelen** [comment]
Very interesting! I have a sneaking suspicion of what the issue might be, but it's hard to diagnose and remedy without being able to reproduce the issue.

I added some more verbose debug prints around my HexRays painting code with commit 11f108b. Can you clone the develop branch, and install that version?

I will need you F5 the function that is not working (like you did in the image above) and send me the log. 

Logs can be found in `C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\lighthouse_logs`

Hopefully your log should look kind of like this: https://gist.github.com/gaasedelen/af3d4e95c302f16b46c03257fd0ec9b7

Thanks :-)

**Comment by gaasedelen** [comment]
Someone else reported this to me and I was able to further debug what I presume to be this issue. Commit 2e88ffb on the develop branch should resolve this :-)
