### ISSUE TITLE
pin 3.11 compilation error

### ISSUE THREAD

**Issue by 0x410c** [gaasedelen/lighthouse#75]
on 3.11 **string** gave **unidentified identifier** error on compiling,
add 

`using namespace std;`

to compile.

**Comment by aaaddress1** [comment]
thanks!

> on 3.11 string gived unidentified indentifier error on compiling,
> add
> 
> `using namespace std;`
> 
> to compile.

thanks! it's useful. I meet the same trouble.

**Comment by gaasedelen** [comment]
Thanks! Sounds like a few people found your issue useful :-) 

These changes have been merged onto the lighthouse develop branch (#77).
