### ISSUE TITLE
Expose Lighthouse's internal state / DatabaseCoverage objects to disassembler interpreter

### ISSUE THREAD

**Issue by 0x410c** [gaasedelen/lighthouse#76]
can i get coverage related data in the python api of ida?

so that the data could be processed further?

ps awesome work!

**Comment by gaasedelen** [comment]
Thanks for the kind words, and sorry for the late response. I'm only catching up on lighthouse maintenance now...

I have been thinking about adding access to this through the IDA / python API for a long time, and am hoping to sneak at least something primitive into the next release of Lighthouse.

I am not sure what the best way is do this is yet, but it will probably involve exposing the live plugin state as a global such that you can extract information from the `CoverageDirector` and the `DatabaseCoverage` objects which are both pretty clean, and should have most of what you want.

I can't promise driving the plugin 'headlessly' will be stable, but at least reading info out should mostly be okay :-)

**Comment by gaasedelen** [comment]
Somewhat related to #34

**Comment by 0x410c** [comment]
great, the idea is not to drive it headless, but to get the data set, so that it can be used in automation!

**Comment by gaasedelen** [comment]
With commit 0ef5c9d9e13fb66623ab1b1cbc2b8110aa5e7982 on the development branch, I have exposed the live instance of Lighthouse's `CoverageDirector` object. This is the most 'user' oriented object / 'API' in lighthouse, and should give you access to everything you need coverage wise:

![image](https://user-images.githubusercontent.com/9522648/77861094-f7aacb80-71e0-11ea-903f-4e43da91e4f9.png)

Right now, the only usecase I will pretend to be supporting is read access to stuff like the coverage data. I would be not try to 'drive' the plugin UI / state through the director as things might explode.

```python

# get access to the live, exposed CoverageDirector instance
from lighthouse import coverage_director

# get the list of NodeCoverage from the DatabaseCoverage object that is active in the UI
coverage_director.coverage.nodes

# request a loaded DatabaseCoverage object by name, or shorthand symbol:
cov_a = coverage_director.get_coverage('A')
print(cov_a.nodes)
```

Please refer to `director.py` or `coverage.py` for more reference.
