### ISSUE TITLE
Feature Request: Support for Python3.x (IDA 7.4+)

### ISSUE THREAD

**Issue by 6a7070** [gaasedelen/lighthouse#82]
IDA 7.4 and future releases will use Python 3.x for plugins. Would you consider supporting Python 3.x for Lighthouse in order to provide future compatibility? Thank you for a great project!

**Comment by gaasedelen** [comment]
Please use the development branch: https://github.com/gaasedelen/lighthouse/tree/develop

v0.9.0 should be released in the coming weeks :-)
