### ISSUE TITLE
Metaclass Conflict

### ISSUE THREAD

**Issue by rnui2k** [gaasedelen/lighthouse#85]
# Error
```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

# Steps to reproduce
mkdir temp && cd temp
git clone https://github.com/gaasedelen/lighthouse
cp -r lighthouse/plugin/* ~/.binaryninja/plugins
\<Start Binary ninja\>

# Setup info
Binary Ninja Version: 2.0.2123-dev
Binary Ninja Python Interpreter: python3.7m.so
Python: 3.7.3
Installed Packages: Pyqt4, pyqt5
OS: Linux
Distro: Debian Buster

# Additional information
From toying around, I believe it is the following line that is causing the issue in lighthouse_plugin.py
``` 
from lighthouse.integration.binja_loader import *
```

# Error Message
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/xxx/.binaryninja/plugins/lighthouse/integration/binja_loader.py", line 3, in <module>
    from lighthouse.util.log import lmsg
  File "/home/xxx/.binaryninja/plugins/lighthouse/util/__init__.py", line 3, in <module>
    from .debug import *
  File "/home/xxx/.binaryninja/plugins/lighthouse/util/debug.py", line 6, in <module>
    from .log import lmsg
  File "/home/xxx/.binaryninja/plugins/lighthouse/util/log.py", line 6, in <module>
    from .disassembler import disassembler
  File "/home/xxx/.binaryninja/plugins/lighthouse/util/disassembler/__init__.py", line 31, in <module>
    from .binja_api import BinjaCoreAPI, BinjaContextAPI
  File "/home/xxx/.binaryninja/plugins/lighthouse/util/disassembler/binja_api.py", line 356, in <module>
    class DockableWidget(QtWidgets.QWidget, DockContextHandler):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by gaasedelen** [comment]
Thanks for the detailed report! I will try to reproduce what is going on here. 

Just to clarify, when you say you have Pyqt4 and Pyqt5 packages installed, did you pip install those / are they separate from the Binary Ninja install? I'm just speculating, but I think your packages might be conflicting with the PyQt5 bindings Binary Ninja ships...

Otherwise, there's a very slim chance it could be that something about class inheritance changed in Python 3.7 ... but I think that is unlikely.

**Comment by rnui2k** [comment]
Following up. 

I had both repository package installed and pip package installed (I live extra dangerous). Removing both pyqt5 installations seemed to do the trick.

Surely I have broken something somewhere else, but I'll deal with it when I deal with it.

Thank you for your help.

**Comment by gaasedelen** [comment]
Thanks for following up! I am glad that was the issue.

Practically speaking, there is no reason anyone should have external PyQt/PySide packages in a Binary Ninja python env anymore. People used to have that when prototyping Binja UI plugins, but now Binary Ninja 2.0/Dev has PySide2 in-box :-)

PS: PyQt / PySide packages can get pretty heavy/messy, so I wouldn't really advise you ever really pip those into your main / system Python install. I'm not an expert at virtual envs, but I break them out when I have to deal with bigger / scarier things like that.
