### ISSUE TITLE
Unsupported disassembler issue

### ISSUE THREAD

**Issue by DigiAngel** [gaasedelen/lighthouse#86]
Having just installed Python 3.7.7, using IDA v 7.4.191112 here what I get on startup with the plugin installed:
~~~
C:\Users\Me\AppData\Roaming\Hex-Rays\IDA Pro\plugins\lighthouse_plugin.py: Unknown or unsupported disassembler!
Traceback (most recent call last):
  File "C:\Apps\IDA\python\3\ida_idaapi.py", line 593, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/Me/AppData/Roaming/Hex-Rays/IDA Pro/plugins/lighthouse_plugin.py", line 1, in <module>
    from lighthouse.util.log import logging_started, start_logging
  File "C:/Users/Me/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\__init__.py", line 3, in <module>
    from .debug import *
  File "C:/Users/Me/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\debug.py", line 6, in <module>
    from .log import lmsg
  File "C:/Users/Me/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\log.py", line 6, in <module>
    from .disassembler import disassembler
  File "C:/Users/Me/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\disassembler\__init__.py", line 42, in <module>
    raise NotImplementedError("Unknown or unsupported disassembler!")
NotImplementedError: Unknown or unsupported disassembler!
~~~

any hints on how to fix this?  Thank you.

**Comment by gaasedelen** [comment]
I just verified that Lighthouse works on Python 3.7.7, I think something is wrong with your install of IDA or you have conflicting versions of Python.

If you try to run this in IDA's Python console, I assume it will fail:
```
from PyQt5 import QtGui
```

This will show you the Python version:

```
import sys; print(sys.version)
```

I think you have two Python 3's installed on your box, and IDA is defaulting to the 3.8 install which does not work correctly with IDA 7.4 and Qt.

Please double check, and use IDA's `idapyswitch.exe` if necessary:

![image](https://user-images.githubusercontent.com/9522648/81335778-25075680-9076-11ea-99c5-39d1c111f22f.png)

IDA's python console should be printing out the following:

![image](https://user-images.githubusercontent.com/9522648/81335953-6ac41f00-9076-11ea-8857-b069f118d151.png)

**Comment by DigiAngel** [comment]
Thanks...I only had the one python installed...had to run idapyswitch which looked exactly like the above with only one option to choose so...eh...who knows :)

**Comment by alex085** [comment]
The same issue. And…
Python 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)] 
IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
