### ISSUE TITLE
Issue loading a drcov trace in Binary Ninja

### ISSUE THREAD

**Issue by thelumberjhack** [gaasedelen/lighthouse#87]
## Issue

Binary Ninja stops responding after I load the attached drcov trace, and need to kill Binja using task manager. I tested the same binary and trace using lighthouse and IDA 7.5 with no issue.

## Configuration:

- Windows 10 2004 in a hyper-v vm with 8 cores and 8GB of RAM
- Binja version 2.0.2170
- Lighthouse version 0.9, commit 710b13f38eaa548109c26ca3cefa68e598682219

## Trace and analyzed PE

[kkrunchy.zip](https://github.com/gaasedelen/lighthouse/files/4759644/kkrunchy.zip)

**Comment by gaasedelen** [comment]
This actually exposed an underlying issue with Binary Ninja's handling of the GIL when it comes to UI plugins. 

I passed along some info to the binja dev's and they were able to fix the real issue without me resorting to hack-y workarounds. Huge kudos to them :-)

Please switch use Binary Ninja Version 2.0.2211-dev (2020-06-12 15:58:26) or newer. It should hopefully no longer be prone to these deadlocks.

Thanks again!
