### ISSUE TITLE
Internal C++ object (CoverageModel) already deleted

### ISSUE THREAD

**Issue by 0vercl0k** [gaasedelen/lighthouse#9]
Loading a coverage file, closing the coverage overview window, and re-opening a coverage file (the same or a different) will trigger the below error message:

```
[Lighthouse] Successfully loaded 1 coverage file(s)...
[Lighthouse] Failed to map coverage D:\cov\drcov.00204.0000.proc.log
[Lighthouse] - Internal C++ object (CoverageModel) already deleted.
[Lighthouse] Successfully loaded 0 coverage file(s)...
```

I'm also hitting a NULL deref in Python at random times (haven't been able to trigger it reliably yet but IDA crashes), and I'm wondering if it's not related to this issue. Let me know when you have a fix so that I can follow-up on this :).

**Comment by gaasedelen** [comment]
The CoverageOverview instantiates a CoverageModel (QAbstractTableModel) which basically formats the director's data in a way the Qt UI (CoverageOverview) can understand/display. 

When you close the CoverageOverview, the underlying Qt object the CoverageModel wraps (QAbstractTableModel) is getting deleted as the Qt widget it is parented to is destroyed by IDA. The python layer that wraps the Qt model is still alive, however. These are the dangers of the PySide/PyQt5 bindings.

The CoverageModel _python_ object is subscribed to signals from director so it knows when coverage is added/changed/deleted etc. 

The notification mechanism inside the director is supposed to be 'smart' and 'self-healing' by removing dead objects/references from its notification wheels. But here it is attempting to notify the CoverageModel of a change (coverage added/updated) after the CoverageOverview was closed and the CoverageModel internal Qt widget deleted.

The proper fix is to ensure the the python references of the CoverageModel get deleted when the CoverageOverview is closed (3b402839f6232cccf103d4493605712ceb2ace7a) and the director should self-heal as expected. I will probably revert (f563be02472d0840b7198616b789a5e94b96231f) as it simply masks the underlying issue in a less than ideal way.
