### ISSUE TITLE
pin plugin in release page is not compatible with the newest pin.

### ISSUE THREAD

**Issue by P4nda0s** [gaasedelen/lighthouse#95]
Pin: pin-3.17-98314-0c048d619
Copyright 2002-2020 Intel Corporation.
E:  Pintool version does not match Pin
Pin:  0c048d619
Tool: c5e41af74

**Comment by gaasedelen** [comment]
Please follow the [instructions](https://github.com/gaasedelen/lighthouse/tree/develop/coverage/pin) to compile the pin tool yourself.
