### ISSUE TITLE
Lighthouse went wrong on dyld_shared_cache on macOS Big Sur.

### ISSUE THREAD

**Issue by singleghost2** [gaasedelen/lighthouse#96]
Hi gaasedelen!
Lighthouse version: 0.9.1

On macOS Big Sur 11.1, there is no problem running coverage analysis against a library, such as AudioCodecs. 

![image](https://user-images.githubusercontent.com/67366879/104696158-cb007a00-5748-11eb-9f9a-b71353566d80.png)

But if this library is integrated in dyld_shared_cache, such as AudioToolboxCore, loading the coverage file in IDA will prompt BAD_COVERAGE_MAPPING error. I tried two situations, one is that only libsystem_c.dylib module is loaded separately in dyld_share_cache, there is no problem. The second case is that libsystem_c.dylib and AudioToolboxCore are loaded in dyld_shared_cache at the same time. At this time, loading the coverage file related to AudioToolboxCore will report the error of BAD_COVERAGE_MAPPING, and the coverage data is all mapped to libsystem_c.dylib. 

![image](https://user-images.githubusercontent.com/67366879/104697101-372fad80-574a-11eb-9596-be6b83a1d7c9.png)

However, there is no error when loading the coverage file related to libsystem_c.dylib.

**Comment by gaasedelen** [comment]
I don't think there's anything I can do about this, Intel Pin itself is not yet supported on Big Sur. 

Closing in favor of #91

**Comment by singleghost2** [comment]
I don’t think this is a PIN problem, because I used tinyinst to generate a drcov format coverage file. I suspect that the lighthouse plugin has a problem with dyld_shared_cache.

**Comment by singleghost2** [comment]
Could you reopen this issue?

**Comment by gaasedelen** [comment]
Tinyinst is not built on Intel Pin.

As of July 6th 2021, Intel Pin (v3.19) is still not supported on Big Sur: https://groups.io/g/pinheads/topic/82069168#13292

**Comment by singleghost2** [comment]
I mean that I use a different coverage collect tool and lighthouse still cannot correctly deal with it in dyld_shared_cache. When ida opens dyld_shared_cache and loads only one module, lighthouse works quite well. But if ida loads several modules in dyld_shared_cache, lighthouse cannot work properly.
