### ISSUE TITLE
Some blocks are skipped despite they exists in drcov file

### ISSUE THREAD

**Issue by expend20** [gaasedelen/lighthouse#97]
Hello! Thank you @gaasedelen for amazing IDA plugin!

I've noticed some bug. Some blocks are not shown/colored in IDA pro but they exist in drcov file. I minimized it to only one basicblock. So, I'm getting NO_COVERAGE_MAPPED exception on next case. 

BB data: RVA 0x13fc, size: 0x3

![image](https://user-images.githubusercontent.com/36543551/106971279-41e0cf80-6757-11eb-8647-c2375aff1aa0.png)

This block should be shown:
```
       1800013fc 48 85 d2        TEST       param_1,param_1
```

[GdiPlus.dll.txt](https://github.com/gaasedelen/lighthouse/files/5929242/GdiPlus.dll.txt)
[1bb.drcov.txt](https://github.com/gaasedelen/lighthouse/files/5929239/1bb.drcov.txt)

Could you have a look?

Thank you in advance!

**Comment by gaasedelen** [comment]
Hi! 

Thank you for providing a testcase! I think that might actually be the first time someone has done that :-)

That said... the test case you provided seems to work just fine for me? 

![image](https://user-images.githubusercontent.com/9522648/106987688-0684d780-673c-11eb-965d-ebcec56a3c92.png)

I tested both on IDA 7.0 w/ Py 2.7, and IDA 7.5 SP3 with Py 3.6.

Can you share any more information?

-Markus

**Comment by expend20** [comment]
Hi Markus! Thank you for quick and thorough response!

I'm sooo sorry, my problem was next. I had tried to apply the coverage file before the auto analysis was finished, thus some coverage was applied and some was not, thus really confused me. All further attempts (for case minimization) were made without waiting for auto analysis finished.

For now everything works perfectly well. I should really have more sleep to avoid such silly mistakes :-P
