### ISSUE TITLE
Failed to parse lasted drcov format 

### ISSUE THREAD

**Issue by treebacker** [gaasedelen/lighthouse#99]
ested on: IDA Pro Version 7.0.170914 Windows x64

To reproduce:

Download the last cronbuild for Windows
https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-8.0.18719/DynamoRIO-Windows-8.0.18719.zip

invoke drcov to generate a .log file to later insert into lighthouse ida PRO
\dynamo\bin32\drrun.exe -t drcov -- calc

Lighthouse fails to open the log file
[Lighthouse] Files reporting PARSE_FAILURE:
[Lighthouse]  - ......log/drcov.calc.exe.14892.0000.proc.log

**Comment by angelystor** [comment]
I made a pull request yesterday that should fix the issue
You can check it out and see if it solves your problem!

**Comment by treebacker** [comment]
Cool, the pull solved my problem!
Thanks!

**Comment by gaasedelen** [comment]
Thanks for the report, and confirming #98 seems to resolve 👍 

Closing as I merged the PR into dev. Please let me know if you notice any other issues.
